name: CI Frontend

on:
  push:
    branches:
      - "*"
  pull_request:
    branches:
      - "*"

jobs:
  ci:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@d23441a48e516b6c34aea4fa41551a30e30af803 # v6
      - run: curl -fsSL https://get.pnpm.io/install.sh | bash -
      - run: echo "/home/runner/.local/share/pnpm:$PATH" >> $GITHUB_PATH
      - uses: actions/setup-node@249970729cb0ef3589644e2896645e5dc5ba9c38 # v6
        with:
          node-version: 24
          cache: "pnpm"

      - run: make install
      - run: make lint
      - run: make compile
      - run: make test
